config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "home#index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  devise_scope :users do
    namespace :user, path: "users", module: "users" do
      resources :articles
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, UploadFileUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :articles, dependent:  :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy ]
  # GET /articles or /articles.json
  def index
    @articles = current_user.articles.all

    
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to user_article_path(@article), notice: "記事を作成しました" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to user_article_path(@article), notice: t("articles.notice.update") }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to user_articles_path, notice: "article.notice.destroy" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :photo, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/home/index.html.erb
<div class="max_width_25 text-center">
  <h3>Dach Boards</h3>
  <div class="row">
    <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
      <h4><%= current_user.name %></h4>
      <div class="btn_padding_t_b"><%= link_to "記事一覧", user_articles_path, class: "btn btn-primary width_100" %></div>
      <div class="btn_padding_t_b"><%= link_to "編集", edit_user_registration_path, class: "btn btn-primary width_100" %></div>
      <div class="btn_padding_t_b"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-warning width_100" %> </div>
    <% else %>
      <!-- ユーザーがログインしていなかった時の処理 -->
      <h2> 現在ログインしていません </h2>
      <%= link_to "ログイン", new_user_session_path, class: 'btn btn-success' %> 
      <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-primary' %> 
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopulationInternCurriculum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="text-center">
      <p class="notice"><%= notice %></p>
    </div>
    <%= yield %>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/articles/_form.html.erb
<% provide(:item, "#{item}") %>
<% provide(:btn, "#{item}") %>
<div class="max_width_50">

  <h1 class="text-center"><%= t("#{item}.title") %></h1>

  <%= form_with(model: article, url: url, local: true) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation">
        <h2><%= t("errors.messages.not_saved.other", count: article.errors.count) %></h2>

        <ul>
          <% article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class:"form-control" %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, class:"form-control" %>
    </div>

    <div class="field">
      <%= form.label :photo %><br>
      <%= form.file_field :photo %>
    </div>

    <div class="actions text-center">
      <%= form.submit t("btn.#{btn}_btn"), class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to t("link.back"), user_articles_path %>
</div>

app/views/users/articles/edit.html.erb
<%= render 'form', article: @article, url: user_article_path, item: "edit", btn: "update" %>

app/views/users/articles/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:ja_item, "index.") %>
<% provide(:ja_btn, "btn.") %>

<div class="container text-center">
  <h1><%= t("#{yield(:ja_item)}title") %></h1>
  <%= link_to t("#{yield(:ja_btn)}new_btn"), new_user_article_path, class: "btn btn-primary width_50" %>

  <table class="table align-middle table-sm">
    <thead>
      <tr>
        <th><%= t("#{yield(:ja_item)}t_head1") %></th>
        <th><%= t("#{yield(:ja_item)}t_head2") %></th>
        <th><%= t("#{yield(:ja_item)}t_head3") %></th>
        <th><%= t("#{yield(:ja_item)}t_head4") %></th>
        <th><%= t("#{yield(:ja_item)}t_head5") %></th>
      </tr>
    </thead>

    <tbody class="table-group-divider">
      <tr></tr>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to t("#{yield(:ja_btn)}show_btn"), user_article_path(article), class: "btn btn-primary" %></td>
          <td><%= article.title %></td>
          <td><%= article.content %></td>
          <td><%= image_tag article.photo.url, :size => "200x200" if article.photo.present? %></td>
          <td>
            <%= link_to t("#{yield(:ja_btn)}edit_btn"), edit_user_article_path(article), class: "btn btn-success" %>
            <%= link_to t("#{yield(:ja_btn)}destroy_btn"), user_article_path(article), method: :delete, data: { confirm: t('confirm.are_you_sure?'), are_you_sure?: article.title }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/articles/new.html.erb
<%= render 'form', article: @article, url: user_articles_path, item: "new", btn: "create" %>

app/views/users/articles/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:ja_item, "show.") %>
<% provide(:ja_btn, "btn.") %>

<div class="container text-center">
  <h1><%= t("#{yield(:ja_item)}title") %></h1>

  <table class="table align-middle">
    <thead>
      <tr>
        <th><%= t("#{yield(:ja_item)}t_head1") %></th>
        <th><%= t("#{yield(:ja_item)}t_head2") %></th>
        <th><%= t("#{yield(:ja_item)}t_head3") %></th>
      </tr>
    </thead>

    <tbody class="table-group-divider">
      <tr>
        <td><%= @article.title %></td>
        <td><%= @article.content %></td>
        <td><%= image_tag @article.photo.url, :size => "200x100" if @article.photo.present? %></td>
      </tr>
    </tbody>
  </table>
  <div class="display_flex">
    <%= link_to t("#{yield(:ja_btn)}edit_btn"), edit_user_article_path(@article), class: "btn btn-success" %>
    <%= link_to t("#{yield(:ja_btn)}destroy_btn"), user_article_path(@article), method: :delete, data: { confirm: t('confirm.are_you_sure?'), are_you_sure?: @article.title }, class: "btn btn-danger padding_left" %>
  </div>
  <div class="padding_top20">
    <%= link_to t("#{yield(:ja_btn)}back_index_btn"), user_articles_path, class: "btn btn-primary" %>
  </div>
</div>